import { createFileRoute, Link } from "@tanstack/react-router";
import heroImg from "@/assets/hero.jpg";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { SiteLayout } from "@/components/site/SiteLayout";
import { HomeOfferSections } from "@/components/home/HomeOfferSections";
import { AdSlot } from "@/components/ads/AdSlot";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Search, ShoppingBag, HandCoins, Leaf, Sparkles, Store, TrendingUp } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [ { title: "Last Bite — Save good food. Pay less. Reduce waste." }, { name: "description", content: "Brunei's surplus food marketplace. Reserve discounted meals from local bakeries, cafes, restaurants and supermarkets before closing." }, { property: "og:title", content: "Last Bite — Surplus food, fair price" }, { property: "og:description", content: "Save good food from local Brunei businesses at fair prices." } ] }),
  component: Landing
});

function Landing() {
  const [merchants, setMerchants] = useState<any[]>([]);
  const [listings, setListings] = useState<any[]>([]);
  useEffect(() => { (async () => {
    const [{ data: m }, { data: l }] = await Promise.all([
      (supabase as any).from("merchants_public").select("id, business_name, business_type, district, image_url").order("created_at", { ascending: false }).limit(6),
      (supabase as any).from("listings").select("*, merchants_public!inner(business_name, district, rating)").eq("visible", true).eq("status", "active").order("created_at", { ascending: false }).limit(12),
    ]);
    setMerchants(m ?? []);
    setListings((l ?? []).map((d: any) => ({ id: d.id, title: d.title, category: d.category, original_price: Number(d.original_price), discounted_price: Number(d.discounted_price), quantity_available: d.quantity_available, pickup_start: d.pickup_start, pickup_end: d.pickup_end, created_at: d.created_at, produced_at: d.produced_at, image_url: d.image_url || "", merchant: { business_name: d.merchants_public?.business_name ?? "", district: d.merchants_public?.district ?? "", rating: Number(d.merchants_public?.rating ?? 0) } })));
  })(); }, []);

  return <SiteLayout>
    <section className="relative overflow-hidden"><div className="container mx-auto grid items-center gap-10 px-4 pb-12 pt-10 md:grid-cols-2 md:pb-20 md:pt-16"><div className="space-y-6"><span className="inline-flex items-center gap-2 rounded-full border bg-cream px-3 py-1 text-xs font-medium"><Sparkles className="h-3.5 w-3.5 text-accent" /> Now serving Brunei Darussalam</span><h1 className="text-4xl font-bold leading-[1.05] md:text-6xl">Save good food. <span className="text-primary">Pay less.</span><br /> Reduce waste.</h1><p className="max-w-lg text-lg text-muted-foreground">Discover surprise bags and surplus meals from local bakeries, cafes, restaurants, hotels and supermarkets before they close.</p><div className="flex flex-wrap gap-3"><Button asChild size="lg" className="rounded-full"><Link to="/browse"><Search className="mr-2 h-4 w-4" /> Browse Food</Link></Button><Button asChild size="lg" variant="outline" className="rounded-full"><Link to="/merchant/onboarding"><Store className="mr-2 h-4 w-4" /> Join as Merchant</Link></Button></div><div className="grid gap-3 pt-2 text-sm text-muted-foreground sm:grid-cols-3"><TrustPoint title="Support local" body="Buy from Brunei food businesses." /><TrustPoint title="Reduce waste" body="Help rescue good food." /><TrustPoint title="Simple pickup" body="Reserve and collect in-store." /></div></div><div className="relative"><img src={heroImg} alt="Fresh pastries from a local bakery" width={1536} height={1024} className="aspect-[4/3] w-full rounded-3xl object-cover shadow-xl" /><Card className="absolute -bottom-4 -left-4 hidden w-64 rounded-2xl p-4 shadow-lg sm:block"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Leaf className="h-5 w-5" /></div><div><div className="text-sm font-semibold">Every rescued meal helps</div><div className="text-xs text-muted-foreground">Support local businesses and reduce waste.</div></div></div></Card></div></div></section>
    <div className="container mx-auto px-4"><AdSlot size="billboard" id="home-hero-billboard" label="Hero billboard" /></div>
    <Section title="How it works" subtitle="Three simple steps from craving to collection."><div className="grid gap-6 md:grid-cols-3">{[{ icon: Search, title: "Discover", body: "Find surprise bags and surplus food near you, filtered by district and category." }, { icon: ShoppingBag, title: "Reserve", body: "Reserve your food and get a pickup code to show the merchant." }, { icon: HandCoins, title: "Collect & enjoy", body: "Drop by during the pickup window. Show your code and take the food home." }].map((s) => <Card key={s.title} className="rounded-3xl border-border/60 p-6"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary text-primary-foreground"><s.icon className="h-6 w-6" /></div><h3 className="mt-4 text-lg font-semibold">{s.title}</h3><p className="mt-1 text-sm text-muted-foreground">{s.body}</p></Card>)}</div></Section>
    {merchants.length > 0 && <Section title="Featured merchants" subtitle="Click a merchant to view their profile, today's offers, and past offers."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{merchants.map((m) => <Link key={m.id} to="/merchant-profile/$id" params={{ id: m.id }} className="group block focus:outline-none focus-visible:ring-2 focus-visible:ring-primary rounded-3xl"><Card className="overflow-hidden rounded-3xl p-0 transition group-hover:-translate-y-1 group-hover:shadow-lg">{m.image_url ? <img src={m.image_url} alt={m.business_name} loading="lazy" className="h-36 w-full object-cover transition group-hover:scale-105" /> : <div className="h-36 w-full bg-muted" />}<div className="p-4"><div className="font-semibold group-hover:text-primary">{m.business_name}</div><div className="text-sm text-muted-foreground">{m.business_type} · {m.district}</div><div className="mt-3 text-xs font-medium text-primary">View vendor profile →</div></div></Card></Link>)}</div></Section>}
    <div className="container mx-auto px-4"><AdSlot size="leaderboard" id="home-mid-leaderboard" label="Sponsored" /></div><HomeOfferSections listings={listings} />
    <Section title="Why people love Last Bite"><div className="grid gap-6 md:grid-cols-2"><BenefitCard title="For customers" items={["Find surplus food from local businesses", "Discover new local favourites", "Simple pickup with QR code"]} /><BenefitCard title="For businesses" items={["List unsold inventory", "Reach nearby customers", "Reduce food waste", "Simple dashboard, no extra hardware"]} /></div></Section>
    <Section title="Food waste impact"><Card className="overflow-hidden rounded-3xl border-border/60 bg-primary text-primary-foreground p-8 md:p-12"><div className="max-w-3xl"><h3 className="text-2xl font-bold md:text-3xl">Small choices can reduce food waste.</h3><p className="mt-3 text-primary-foreground/85">Last Bite helps connect customers with surplus food from local businesses, making it easier to support merchants while giving good food another chance.</p></div></Card></Section>
    <Section title="Frequently asked questions"><div className="mx-auto max-w-3xl"><Accordion type="single" collapsible className="w-full">{[{ q: "Is the food safe to eat?", a: "Merchants are responsible for listing food that is fresh and within safe consumption windows, including any allergen information customers need." }, { q: "What is a surprise bag?", a: "A bag of unsold items chosen by the merchant. The exact contents may vary depending on what is available." }, { q: "How do I pay?", a: "For now, payment is made directly to the merchant during pickup." }, { q: "Can I cancel a reservation?", a: "You can cancel before collection, but please only reserve food you intend to pick up." }].map((f, i) => <AccordionItem key={i} value={`q-${i}`}><AccordionTrigger>{f.q}</AccordionTrigger><AccordionContent>{f.a}</AccordionContent></AccordionItem>)}</Accordion></div></Section>
  </SiteLayout>;
}
function Section({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) { return <section className="container mx-auto px-4 py-14 md:py-20"><div className="mb-8 max-w-2xl"><h2 className="text-3xl font-bold md:text-4xl">{title}</h2>{subtitle && <p className="mt-2 text-muted-foreground">{subtitle}</p>}</div>{children}</section>; }
function TrustPoint({ title, body }: { title: string; body: string }) { return <div><div className="font-semibold text-foreground">{title}</div><div>{body}</div></div>; }
function BenefitCard({ title, items }: { title: string; items: string[] }) { return <Card className="rounded-3xl p-6"><h3 className="text-xl font-semibold">{title}</h3><ul className="mt-4 space-y-3 text-sm">{items.map((it) => <li key={it} className="flex items-start gap-2"><TrendingUp className="mt-0.5 h-4 w-4 text-primary" /><span>{it}</span></li>)}</ul></Card>; }
