/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserGuideRouteImport } from './routes/user-guide'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as MerchantOnboardingRouteImport } from './routes/merchant.onboarding'
import { Route as MerchantNewListingRouteImport } from './routes/merchant.new-listing'
import { Route as MerchantProfileIdRouteImport } from './routes/merchant-profile.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalMerchantAgreementRouteImport } from './routes/legal.merchant-agreement'
import { Route as LegalFoodSafetyRouteImport } from './routes/legal.food-safety'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as MerchantEditListingIdRouteImport } from './routes/merchant.edit-listing.$id'

const UserGuideRoute = UserGuideRouteImport.update({
  id: '/user-guide',
  path: '/user-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/merchant/',
  path: '/merchant/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantOnboardingRoute = MerchantOnboardingRouteImport.update({
  id: '/merchant/onboarding',
  path: '/merchant/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantNewListingRoute = MerchantNewListingRouteImport.update({
  id: '/merchant/new-listing',
  path: '/merchant/new-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantProfileIdRoute = MerchantProfileIdRouteImport.update({
  id: '/merchant-profile/$id',
  path: '/merchant-profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMerchantAgreementRoute = LegalMerchantAgreementRouteImport.update({
  id: '/legal/merchant-agreement',
  path: '/legal/merchant-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalFoodSafetyRoute = LegalFoodSafetyRouteImport.update({
  id: '/legal/food-safety',
  path: '/legal/food-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantEditListingIdRoute = MerchantEditListingIdRouteImport.update({
  id: '/merchant/edit-listing/$id',
  path: '/merchant/edit-listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/user-guide': typeof UserGuideRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/legal/food-safety': typeof LegalFoodSafetyRoute
  '/legal/merchant-agreement': typeof LegalMerchantAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/listing/$id': typeof ListingIdRoute
  '/merchant-profile/$id': typeof MerchantProfileIdRoute
  '/merchant/new-listing': typeof MerchantNewListingRoute
  '/merchant/onboarding': typeof MerchantOnboardingRoute
  '/order/$id': typeof OrderIdRoute
  '/merchant/': typeof MerchantIndexRoute
  '/merchant/edit-listing/$id': typeof MerchantEditListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/user-guide': typeof UserGuideRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/legal/food-safety': typeof LegalFoodSafetyRoute
  '/legal/merchant-agreement': typeof LegalMerchantAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/listing/$id': typeof ListingIdRoute
  '/merchant-profile/$id': typeof MerchantProfileIdRoute
  '/merchant/new-listing': typeof MerchantNewListingRoute
  '/merchant/onboarding': typeof MerchantOnboardingRoute
  '/order/$id': typeof OrderIdRoute
  '/merchant': typeof MerchantIndexRoute
  '/merchant/edit-listing/$id': typeof MerchantEditListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/user-guide': typeof UserGuideRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/legal/food-safety': typeof LegalFoodSafetyRoute
  '/legal/merchant-agreement': typeof LegalMerchantAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/listing/$id': typeof ListingIdRoute
  '/merchant-profile/$id': typeof MerchantProfileIdRoute
  '/merchant/new-listing': typeof MerchantNewListingRoute
  '/merchant/onboarding': typeof MerchantOnboardingRoute
  '/order/$id': typeof OrderIdRoute
  '/merchant/': typeof MerchantIndexRoute
  '/merchant/edit-listing/$id': typeof MerchantEditListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/messages'
    | '/reset-password'
    | '/user-guide'
    | '/checkout/$id'
    | '/legal/food-safety'
    | '/legal/merchant-agreement'
    | '/legal/privacy'
    | '/legal/terms'
    | '/listing/$id'
    | '/merchant-profile/$id'
    | '/merchant/new-listing'
    | '/merchant/onboarding'
    | '/order/$id'
    | '/merchant/'
    | '/merchant/edit-listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/messages'
    | '/reset-password'
    | '/user-guide'
    | '/checkout/$id'
    | '/legal/food-safety'
    | '/legal/merchant-agreement'
    | '/legal/privacy'
    | '/legal/terms'
    | '/listing/$id'
    | '/merchant-profile/$id'
    | '/merchant/new-listing'
    | '/merchant/onboarding'
    | '/order/$id'
    | '/merchant'
    | '/merchant/edit-listing/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/dashboard'
    | '/messages'
    | '/reset-password'
    | '/user-guide'
    | '/checkout/$id'
    | '/legal/food-safety'
    | '/legal/merchant-agreement'
    | '/legal/privacy'
    | '/legal/terms'
    | '/listing/$id'
    | '/merchant-profile/$id'
    | '/merchant/new-listing'
    | '/merchant/onboarding'
    | '/order/$id'
    | '/merchant/'
    | '/merchant/edit-listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  MessagesRoute: typeof MessagesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UserGuideRoute: typeof UserGuideRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  LegalFoodSafetyRoute: typeof LegalFoodSafetyRoute
  LegalMerchantAgreementRoute: typeof LegalMerchantAgreementRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ListingIdRoute: typeof ListingIdRoute
  MerchantProfileIdRoute: typeof MerchantProfileIdRoute
  MerchantNewListingRoute: typeof MerchantNewListingRoute
  MerchantOnboardingRoute: typeof MerchantOnboardingRoute
  OrderIdRoute: typeof OrderIdRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
  MerchantEditListingIdRoute: typeof MerchantEditListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-guide': {
      id: '/user-guide'
      path: '/user-guide'
      fullPath: '/user-guide'
      preLoaderRoute: typeof UserGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/merchant'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/onboarding': {
      id: '/merchant/onboarding'
      path: '/merchant/onboarding'
      fullPath: '/merchant/onboarding'
      preLoaderRoute: typeof MerchantOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/new-listing': {
      id: '/merchant/new-listing'
      path: '/merchant/new-listing'
      fullPath: '/merchant/new-listing'
      preLoaderRoute: typeof MerchantNewListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-profile/$id': {
      id: '/merchant-profile/$id'
      path: '/merchant-profile/$id'
      fullPath: '/merchant-profile/$id'
      preLoaderRoute: typeof MerchantProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/merchant-agreement': {
      id: '/legal/merchant-agreement'
      path: '/legal/merchant-agreement'
      fullPath: '/legal/merchant-agreement'
      preLoaderRoute: typeof LegalMerchantAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/food-safety': {
      id: '/legal/food-safety'
      path: '/legal/food-safety'
      fullPath: '/legal/food-safety'
      preLoaderRoute: typeof LegalFoodSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/edit-listing/$id': {
      id: '/merchant/edit-listing/$id'
      path: '/merchant/edit-listing/$id'
      fullPath: '/merchant/edit-listing/$id'
      preLoaderRoute: typeof MerchantEditListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  MessagesRoute: MessagesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UserGuideRoute: UserGuideRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  LegalFoodSafetyRoute: LegalFoodSafetyRoute,
  LegalMerchantAgreementRoute: LegalMerchantAgreementRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ListingIdRoute: ListingIdRoute,
  MerchantProfileIdRoute: MerchantProfileIdRoute,
  MerchantNewListingRoute: MerchantNewListingRoute,
  MerchantOnboardingRoute: MerchantOnboardingRoute,
  OrderIdRoute: OrderIdRoute,
  MerchantIndexRoute: MerchantIndexRoute,
  MerchantEditListingIdRoute: MerchantEditListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
